apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-project-deployment
  labels:
    app: my-devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-devops-project
  template:
    metadata:
      labels:
        app: my-devops-project
    spec:
      containers:
      - name: my-devops-project-container
        image: hemanthf5/my-devops-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000