apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:   
  name: my-devops-project-secretproviderclass
spec: 
  provider: aws
  parameters:
   usePodIdentity: "true"
   objects: |
    - objectName: "my-devops-project-secrets"
      objectType: "secretsmanager"
      jmesPath:
        - path: "db_user"
          objectAlias: "db_user"
        - path: "db_password"
          objectAlias: "db_password"
        
