apiVersion: v1
kind: Service
metadata:
  name: my-devops-project
  labels:
    app: my-devops-project
spec:
  type: ClusterIP
  
  selector:
    app: my-devops-project
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  
  